global.USERNAME_IS_EMPTY = 'USERNAME_IS_EMPTY';
global.PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
global.PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
    'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8';
global.WRONG_PASSWORD = 'WRONG_PASSWORD';
global.SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';
global.USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY';
global.USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
global.TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY';
global.EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT';
global.PLAN_NOT_FOUND = 'PLAN_NOT_FOUND';
global.NAME_IS_EMPTY = 'NAME_IS_EMPTY';



